name: Build and deploy MaintainenceAPI to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Restore dependencies
        run: dotnet restore MaintainenceAPI/MaintainenceAPI.csproj

      - name: Build project
        run: dotnet build MaintainenceAPI/MaintainenceAPI.csproj --configuration Release --no-restore

      - name: Publish project
        run: dotnet publish MaintainenceAPI/MaintainenceAPI.csproj -c Release -o publish

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: maintainenceapi
          path: publish

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: maintainenceapi

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: maintenance-webapi-26
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: .
